/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>
#include <iostream>
using namespace std;


/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 121
#define YY_END_OF_BUFFER 122
static yyconst short int yy_accept[358] =
    {   0,
        0,    0,  111,  111,    0,    0,  122,  121,   77,   76,
       78,   96,  121,  120,  121,   97,   93,  121,   81,   82,
       91,   89,   88,   90,   87,   92,  115,  115,   86,   85,
      101,   99,  102,   95,  114,   83,   84,  100,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,   79,   94,   80,   98,  111,
      112,   61,    0,  119,    0,  120,  120,   65,   67,   62,
       73,    0,  118,    0,   64,   53,    0,   68,   54,   69,
      110,   66,  117,    0,  116,  116,  116,  115,   55,   59,
       60,   58,   56,  114,   74,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,   13,  114,  114,  114,  114,
      114,  114,  114,  114,  114,   23,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,   75,   63,
      111,  112,  112,  113,  117,   70,   71,   57,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,   19,  114,  114,  114,
      114,  114,  114,  103,  114,  114,   30,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,   48,   49,  114,  114,  114,  117,

       72,  114,  114,  114,  114,  109,  114,    6,    7,  114,
      108,  114,  114,  114,  114,  114,   14,   15,  114,  114,
      114,  114,  114,   22,  114,  114,  114,  114,  114,  105,
      114,   31,  114,  114,  114,  114,  114,  114,   38,  114,
      114,  114,  114,  114,  114,   44,  114,  114,   50,  114,
      114,  114,  114,  114,    4,  114,    8,    9,   10,  114,
      114,  114,  114,   17,  106,  114,  114,  114,  114,   26,
      114,  114,  114,  114,   33,  114,  114,  114,  114,  114,
      104,  114,   41,  114,  114,   45,  114,  114,   52,  114,
        2,  114,  114,  114,  114,  107,  114,  114,   20,  114,

      114,   25,  114,  114,   29,  114,  114,  114,  114,   37,
       39,   40,   42,  114,   46,  114,  114,  114,    3,    5,
      114,   12,   16,   18,   21,  114,  114,  114,  114,   34,
       35,  114,  114,  114,  114,    1,   11,  114,  114,  114,
       32,  114,  114,  114,   51,  114,  114,   28,   36,  114,
       47,   24,   27,  114,  114,   43,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       29,   30,   31,   32,   28,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   28,   42,   43,   44,   45,
       46,   47,   28,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    1,    1,    3,    1,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    1,    1,
        1,    1,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[367] =
    {   0,
        0,    0,   58,   59,    0,    0,  425,  426,  426,  426,
      426,  399,   57,  416,  414,  396,   54,   54,  426,  426,
      395,   55,  426,   57,  426,   67,   65,   84,  426,  426,
       42,  394,   43,  426,    0,  426,  426,  393,   57,   52,
       68,   51,   67,   72,   79,   51,  371,   87,   79,   84,
      379,   89,   79,   95,  375,  426,  106,  426,  426,    0,
       80,  426,  103,  426,  411,    0,  406,  426,  426,  426,
      426,  123,  426,  409,  426,  426,  125,  426,  426,  426,
      426,  426,  426,  116,  141,  142,  145,  148,  386,  426,
      426,  426,  124,    0,  426,  361,  360,  362,  370,  105,

      121,  373,  372,  359,  365,  351,  352,  349,  349,  353,
      351,  348,  345,  349,  343,    0,  345,  127,  346,  340,
      336,  345,  350,  336,  350,  132,  350,  125,  337,  349,
      334,  339,  334,  117,  134,  330,  138,  336,  426,  426,
        0,  166,  168,  426,  177,  426,  426,  351,  325,  337,
      330,  339,  334,  337,  149,  334,  320,  318,  141,  333,
      331,  327,  319,  325,  328,  327,    0,  308,  321,  311,
      149,  319,  305,  317,  314,  311,    0,  308,  302,  312,
      306,  295,  296,  302,  294,  292,  294,  291,  303,  289,
      303,  288,  290,  290,    0,    0,  298,  300,  289,  426,

      426,  283,  282,  292,  286,    0,  284,    0,    0,  286,
        0,  276,  274,  282,  271,  278,    0,    0,  275,  276,
      268,  269,  268,    0,  278,  266,  265,  279,  263,    0,
      258,    0,  276,  260,  274,  273,  268,  263,    0,  255,
      252,  260,  252,  264,  258,    0,  244,  247,    0,  245,
      257,  260,  242,  258,    0,  239,    0,    0,    0,  244,
      245,  250,  250,  242,    0,  247,  242,  238,  231,    0,
      235,  241,  241,  227,    0,  237,  225,  239,  238,  227,
        0,  236,    0,  230,  221,  219,  226,  225,    0,  230,
        0,  219,  226,  211,  211,    0,  211,  204,    0,  223,

      220,    0,  221,  222,    0,  208,  213,  210,  195,    0,
        0,    0,    0,  196,    0,  195,  171,  163,    0,    0,
      175,    0,    0,    0,    0,  166,  173,  174,  160,    0,
        0,  170,  161,  160,  167,    0,    0,  153,  156,  164,
        0,  164,  155,  144,    0,  144,  150,    0,    0,  128,
        0,    0,    0,  119,  116,    0,  426,  215,  220,  225,
      230,  235,  238,   88,  243,  248
    } ;

static yyconst short int yy_def[367] =
    {   0,
      357,    1,  358,  358,  359,  359,  357,  357,  357,  357,
      357,  357,  360,  361,  357,  357,  357,  362,  357,  357,
      357,  357,  357,  357,  357,  357,  363,  363,  357,  357,
      357,  357,  357,  357,  364,  357,  357,  357,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  357,  357,  357,  357,  365,
      366,  357,  360,  357,  360,  361,  361,  357,  357,  357,
      357,  362,  357,  362,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  363,  363,  363,  363,  357,  357,
      357,  357,  357,  364,  357,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  357,  357,
      365,  366,  366,  357,  357,  357,  357,  357,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  357,

      357,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,    0,  357,  357,  357,
      357,  357,  357,  357,  357,  357
    } ;

static yyconst short int yy_nxt[487] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,    8,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   35,
       46,   35,   47,   35,   48,   49,   50,   51,   52,   53,
       35,   54,   55,   35,   35,   35,   56,   57,   58,   59,
        8,    8,   64,   70,   73,   89,   90,   92,   93,   76,
       83,   61,   61,   79,   77,   77,   77,   77,   71,   78,
       81,   80,   84,   74,   85,   85,   65,  105,  116,   83,
       96,   82,   94,  143,  117,  118,  106,   98,  144,   99,

      101,   84,   87,   88,   88,   97,  100,  102,   64,  107,
      103,  108,  110,  104,  111,  114,  125,  112,  134,  120,
      109,   87,  113,  121,  115,  123,  135,  136,  129,  124,
      139,  126,   65,   73,  127,  145,  145,  122,  130,  131,
      137,  132,   84,  133,   77,   77,  357,  357,  147,  148,
      357,  356,   74,  357,  153,  355,  154,  192,   84,  357,
       85,   85,  357,  140,  193,   84,  194,   88,   88,  155,
      156,  172,  182,  185,  186,  173,  174,  183,  197,  357,
      198,  143,  200,  354,  357,  208,  144,  353,  195,  213,
      214,  225,  352,  351,  226,  350,  145,  145,  209,  349,

      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  200,   60,   60,   60,   60,   60,
        8,    8,    8,    8,    8,   63,   63,   63,   63,   63,
       66,  334,   66,   66,   66,   72,   72,   72,   72,   72,
       86,  333,   86,  141,  332,  141,  331,  141,  142,  330,
      142,  142,  142,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,

      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  212,  211,  210,  207,
      206,  205,  204,  203,  202,  201,  199,  196,  191,  190,
      189,  188,  187,  184,  181,  180,  179,  178,  177,  176,
      175,  171,  170,  169,  168,  167,  166,  165,  164,  163,

      162,  161,  160,  159,  158,  157,  152,  151,  150,  149,
      146,  357,   67,  357,  138,  128,  119,   95,   91,   75,
       69,   68,   67,   62,  357,    7,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357
    } ;

static yyconst short int yy_chk[487] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   13,   17,   18,   31,   31,   33,   33,   22,
       27,    3,    4,   24,   22,   22,   24,   24,   17,   22,
       26,   24,   27,   18,   27,   27,   13,   42,   46,   28,
       39,   26,  364,   61,   46,   46,   42,   40,   61,   40,

       41,   28,   27,   28,   28,   39,   40,   41,   63,   43,
       41,   43,   44,   41,   44,   45,   50,   44,   53,   48,
       43,   28,   44,   48,   45,   49,   53,   54,   52,   49,
       57,   50,   63,   72,   50,   84,   84,   48,   52,   52,
       54,   52,   77,   52,   77,   77,   85,   86,   93,   93,
       87,  355,   72,   88,  100,  354,  100,  134,   85,   86,
       85,   85,   87,   57,  134,   88,  135,   88,   88,  101,
      101,  118,  126,  128,  128,  118,  118,  126,  137,  142,
      137,  143,  145,  350,  142,  155,  143,  347,  135,  159,
      159,  171,  346,  344,  171,  343,  145,  145,  155,  342,

      340,  339,  338,  335,  334,  333,  332,  329,  328,  327,
      326,  321,  318,  317,  145,  358,  358,  358,  358,  358,
      359,  359,  359,  359,  359,  360,  360,  360,  360,  360,
      361,  316,  361,  361,  361,  362,  362,  362,  362,  362,
      363,  314,  363,  365,  309,  365,  308,  365,  366,  307,
      366,  366,  366,  306,  304,  303,  301,  300,  298,  297,
      295,  294,  293,  292,  290,  288,  287,  286,  285,  284,
      282,  280,  279,  278,  277,  276,  274,  273,  272,  271,
      269,  268,  267,  266,  264,  263,  262,  261,  260,  256,
      254,  253,  252,  251,  250,  248,  247,  245,  244,  243,

      242,  241,  240,  238,  237,  236,  235,  234,  233,  231,
      229,  228,  227,  226,  225,  223,  222,  221,  220,  219,
      216,  215,  214,  213,  212,  210,  207,  205,  204,  203,
      202,  199,  198,  197,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  176,  175,  174,  173,  172,  170,  169,  168,  166,
      165,  164,  163,  162,  161,  160,  158,  157,  156,  154,
      153,  152,  151,  150,  149,  148,  138,  136,  133,  132,
      131,  130,  129,  127,  125,  124,  123,  122,  121,  120,
      119,  117,  115,  114,  113,  112,  111,  110,  109,  108,

      107,  106,  105,  104,  103,  102,   99,   98,   97,   96,
       89,   74,   67,   65,   55,   51,   47,   38,   32,   21,
       16,   15,   14,   12,    7,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
#define INITIAL 0
#line 2 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
		#include "yacc.hpp"
		#include <iostream>
		#include <istream>
		#include <ostream>		
		#include <FlexLexer.h>	
		int lineNo = 1;
		int colNo = 1;
		int i;
        float f;
        double d;
#define multilinecomment 1

#define string 2

#line 565 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"

#line 694 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 358 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 426 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return ABSTRACT;
						}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return ASSERT;
						}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return BOOLEAN;
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return BREAK;
						}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return BYVALUE;
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return CASE;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return CAST;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  CATCH;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  CLASS;
						}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 91 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  CONST;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  CONTINUE;
						}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 105 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  DEFAULT;
                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  DO;
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  ELSE;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 127 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  ENUM;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext); 
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  EXTENDS;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  FINAL;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 148 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  FINALLY;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 155 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  FOR;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 162 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  FUTURE;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  GENERIC;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 177 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  GOTO;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 184 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  IF;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 191 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  IMPLEMENTS;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 198 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  IMPORT;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 205 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  INNER;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 212 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  INSTANCEOF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 219 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  INTERFACE;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 226 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  NATIVE;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 233 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return	NEW;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 241 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  JNULL;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 248 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  OPERATOR;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 255 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  OUTER;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 262 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  PACKAGE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 269 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  PRIVATE;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 276 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  PROTECTED;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 283 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  PUBLIC;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 291 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
                            colNo += strlen(yytext);
                            yylval.r.myLineNo= lineNo; 
                            yylval.r.myColno = colNo; 
                            return  REST;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 298 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  RETURN;
						}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 305 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  STATIC;
						}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 312 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  SUPER;
						}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 319 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  SWITCH;
						}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 326 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  SYNCHRONIZED;
						}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 333 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return	THIS;
						}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 340 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  THROW;
						}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 347 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  THROWS;
						}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 354 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  TRANSIENT;
						}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 361 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  TRY;
						}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 368 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  VAR;
						}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 375 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  VOID;
						}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 382 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  VOLATILE;
						}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 389 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  STATIC;
						}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 396 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_INC;
						}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 403 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_DEC;
						}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 410 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_SHL;
						}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 417 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_SHR;
						}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 424 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_SHRR;
						}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 431 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_GE;
						}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 438 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_LE;
						}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 445 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_EQ;
						}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 452 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_NE;
						}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 459 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_LAND;
						}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 466 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_LOR;
						}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 473 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_MUL;
						}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 480 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  OP_DIM;
						}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 487 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_DIV;
						}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 494 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_MOD;
						}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 501 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_ADD;
						}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 508 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_SUB;
						}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 515 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext);
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_SHL;
						}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 522 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_SHR;
						}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 529 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_SHRR;
						}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 536 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_AND;
						}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 543 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_XOR;
						}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 550 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  ASS_OR;
						}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 557 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							lineNo = lineNo+1;
							colNo = 1;
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
						}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 564 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += 4;
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
						}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 570 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += 1;
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
						}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 576 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return OPEN_D;
						}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 583 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return CLOSE_D;
						}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 590 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return OPEN_B;
						}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 597 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return CLOSE_B;
						}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 604 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return OPEN;
						}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 611 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return CLOSE;
						}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 618 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return SEMICOLON;
						}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 625 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return COLON;
						}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 632 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return POINT;
						}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 639 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return COMMA;
						}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 646 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return PLUS;
						}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 653 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return MINUS;
						}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 660 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return MULT;
						}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 667 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return DIV;
						}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 674 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return AND;
						}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 681 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return OR;
						}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 688 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return QUES_MARK;
						}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 695 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return EXC_MARK;
						}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 702 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return MODULE;
						}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 709 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return DURA;
						}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 716 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return ASSIGN;
						}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 723 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return XOR;
						}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 730 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return LESS;
						}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 737 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							return GREATER;
						}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 744 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo;
							int i = atoi(yytext);
							yylval.r.i=i;
							return INT;
						}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 753 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							int i = atoi(yytext);
							yylval.r.i=i;
							return SHORT;
						}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 762 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							int i = atoi(yytext);
							yylval.r.i=i;
							return  LONG;
						}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 771 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							float f = atof(yytext);
							yylval.r.i=f;
							return	FLOAT;
						}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 780 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							double d= atof(yytext);
							yylval.r.f = d;
							return  DOUBLE;
						}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 789 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  CHAR;
						}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 796 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							colNo += strlen(yytext); 
							yylval.r.myLineNo= lineNo; 
							yylval.r.myColno = colNo; 
							return  BYTE;
						}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 806 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{ BEGIN multilinecomment; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 807 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 808 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{lineNo++;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 809 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{ BEGIN INITIAL;cout<<"\t it is a Multi Line Comment \n";}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 812 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{	
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							char * x=new char [255];
							x[0] = '\0';
							strcpy(x, yytext);
							yylval.r.str = x;
							return IDENTIFIER;
						}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 823 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							cout<<":Integer value (yytext) ="<<yytext<<"\n";
							int i = atoi(yytext);
							cout<<":Int value as int ="<<i;
							yylval.r.i = i;
							if(strlen(yytext) <= 4)
								return INTEGER_VALUE;
							else
								return LONG_VALUE;
						}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 837 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							char * x=new char [255];
							x[0] = '\0';
							strcpy(x, yytext);
							yylval.r.str = x;
							return N_ID;
						}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 848 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							cout<<":Float value (yytext) ="<<yytext<<"\n";
							float f = atof(yytext);
							cout<<":Float value as float ="<<f;
							yylval.r.f = f;
							return FLOAT_VALUE;
						}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 859 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);

							char * x=new char [strlen(yytext)-2];
							x[0] = '\0';
							strncpy(x, yytext+1 , strlen(yytext) - 2);
							x[strlen(yytext) - 2]= '\0';
							yylval.r.c = *x;
							return CHAR_VALUE;
						}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 872 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							char * s=new char [strlen(yytext)-2];
							s[0] = '\0';
							strncpy(s, yytext + 1, strlen(yytext) - 2);
							s[strlen(yytext) - 2] = '\0';
							//strcpy(yylval.r.str,s);
							yylval.r.str = s;
							return	STRING_VALUE;
						}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 885 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
{
							yylval.r.myColno = colNo;
							yylval.r.myLineNo = lineNo;
							colNo += strlen(yytext);
							//cout<<"\t comment\n";
						}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 893 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"
ECHO;
	YY_BREAK
#line 1999 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(multilinecomment):
case YY_STATE_EOF(string):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 358 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 358 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 357);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 893 "C:\\Users\\Amany Obied\\Documents\\Visual Studio 2013\\Projects\\JavaCompiler\\lex.l"


